from django.db import models

# Create your models here.

class presupuest_recieve(models.Model):
    # Watersheed general data
    watersheed = models.CharField(max_length = 500, null = True, blank = True)
    #watersheed_area = models.IntegerField(null = True, blank = True)
    #corporations = models.CharField(max_length = 20, null = True, blank = True)
    #pomca_type = models.CharField(max_length = 15, null = True, blank = True)
    #pomca_comunity = models.CharField(max_length = 500, null = True, blank = True)
    #pomca_comunity_quant = models.IntegerField(null = True, blank = True)
    #pomca_comunity_located = models.CharField(max_length = 500, null = True, blank = True)
    #pomca_park = models.CharField(max_length = 500, null = True, blank = True)
    #villages = models.IntegerField(null = True, blank = True)
    # Aprestamiento phase
    aprest_transpor_quant = models.FloatField(null = True, blank = True)
    #aprest_transpor_cantidad = models.IntegerField(null = True, blank = True)
    aprest_estaciones_quant = models.IntegerField(null = True, blank = True)
    aprest_estaciones_cost = models.FloatField(null = True, blank = True)
    #aprest_part_actor_municipi = models.IntegerField(null = True, blank = True)
    aprest_part_actor_cost = models.FloatField(null = True, blank = True)
    aprest_part_tecni_cost = models.FloatField(null = True, blank = True)
    #aprest_divulga_quant = models.IntegerField(null = True, blank = True)
    aprest_divulga_cost = models.FloatField(null = True, blank = True)
    aprest_maps_quant = models.IntegerField(null = True, blank = True)
    aprest_maps_cost = models.FloatField(null = True, blank = True)
    aprest_docs_quant = models.IntegerField(null = True, blank = True)
    aprest_docs_cost = models.FloatField(null = True, blank = True)
    # Diagnostico phase
    diag_transpor_quant = models.FloatField(null = True, blank = True)
    diag_log_const_cost = models.FloatField(null = True, blank = True)
    diag_log_diagact_quant = models.IntegerField(null = True, blank = True)
    diag_log_diagact_cost = models.FloatField(null = True, blank = True)
    #diag_log_espact_quant = models.IntegerField(null = True, blank = True)
    diag_log_espact_cost = models.FloatField(null = True, blank = True)
    diag_log_tec_cost = models.FloatField(null = True, blank = True)
    #diag_divul_quant = models.IntegerField(null = True, blank = True)
    diag_divul_cost = models.FloatField(null = True, blank = True)
    diag_estudio_coberturas = models.FloatField(null = True, blank = True)
    diag_estudio_coberturas_cost = models.FloatField(null = True, blank = True)
    diag_estudio_multitemporal = models.FloatField(null = True, blank = True)
    diag_estudio_multitemporal_cost = models.FloatField(null = True, blank = True)
    diag_estudio_plana = models.FloatField(null = True, blank = True)
    diag_estudio_plana_cost = models.FloatField(null = True, blank = True)
    diag_estudio_ladera = models.FloatField(null = True, blank = True)
    diag_estudio_ladera_cost = models.FloatField(null = True, blank = True)
    diag_estudio_geologica = models.FloatField(null = True, blank = True)
    diag_estudio_geologica_cost = models.FloatField(null = True, blank = True)
    diag_estudio_hidrodinamina = models.FloatField(null = True, blank = True)
    diag_estudio_hidrodinamina_cost = models.FloatField(null = True, blank = True)
    diag_estudio_electricos = models.IntegerField(null = True, blank = True)
    diag_estudio_electricos_cost = models.IntegerField(null = True, blank = True)
    diag_estudio_caliagua = models.IntegerField(null = True, blank = True)
    diag_estudio_caliagua_cost = models.IntegerField(null = True, blank = True)
    diag_estudio_ecolobosq = models.FloatField(null = True, blank = True)
    diag_estudio_ecolobosq_cost = models.IntegerField(null = True, blank = True)
    diag_estudio_ecoloherb = models.FloatField(null = True, blank = True)
    diag_estudio_ecoloherb_cost = models.IntegerField(null = True, blank = True)
    diag_maps_quant = models.IntegerField(null = True, blank = True)
    diag_maps_cost = models.FloatField(null = True, blank = True)
    diag_docs_quant = models.IntegerField(null = True, blank = True)
    diag_docs_cost = models.FloatField(null = True, blank = True)
    # Prospectiva y zonificacion phase
    zoni_transpor_quant = models.FloatField(null = True, blank = True)
    #zoni_log_act_quant = models.IntegerField(null = True, blank = True)
    zoni_log_act_cost = models.FloatField(null = True, blank = True)
    zoni_log_tec_cost = models.FloatField(null = True, blank = True)
    #zoni_divul_quant = models.IntegerField(null = True, blank = True)
    zoni_divul_cost = models.FloatField(null = True, blank = True)
    zoni_maps_quant = models.IntegerField(null = True, blank = True)
    zoni_maps_cost = models.FloatField(null = True, blank = True)
    zoni_docs_quant = models.IntegerField(null = True, blank = True)
    zoni_docs_cost = models.FloatField(null = True, blank = True)
    # Formulacion phase
    formu_transpor_quant = models.FloatField(null = True, blank = True)
    formu_log_act_cost = models.FloatField(null = True, blank = True)
    #formu_log_act_quant = models.IntegerField(null = True, blank = True)
    formu_log_tec_cost = models.FloatField(null = True, blank = True)
    #formu_divul_quant = models.IntegerField(null = True, blank = True)
    formu_divul_cost = models.FloatField(null = True, blank = True)
    formu_maps_quant = models.IntegerField(null = True, blank = True)
    formu_maps_cost = models.FloatField(null = True, blank = True)
    formu_docs_quant = models.IntegerField(null = True, blank = True)
    formu_docs_cost = models.FloatField(null = True, blank = True)
    # Base professional and thecnic equipment
    director = models.FloatField(null = True, blank = True)
    director_fm = models.FloatField(null = True, blank = True)
    director_via = models.FloatField(null = True, blank = True)
    director_profession = models.CharField(max_length = 1500, null = True, blank = True)
    director_specialist = models.CharField(max_length = 1500, null = True, blank = True)
    director_experience = models.CharField(max_length = 1500, null = True, blank = True)
    director_expspecifi = models.CharField(max_length = 1500, null = True, blank = True)
    exp_partic = models.FloatField(null = True, blank = True)
    exp_partic_fm = models.FloatField(null = True, blank = True)
    exp_partic_via = models.FloatField(null = True, blank = True)
    exp_partic_profession = models.CharField(max_length = 1500, null = True, blank = True)
    exp_partic_specialist = models.CharField(max_length = 1500, null = True, blank = True)
    exp_partic_experience = models.CharField(max_length = 1500, null = True, blank = True)
    exp_partic_expspecifi = models.CharField(max_length = 1500, null = True, blank = True)
    exp_sig = models.FloatField(null = True, blank = True)
    exp_sig_fm = models.FloatField(null = True, blank = True)
    exp_sig_via = models.FloatField(null = True, blank = True)
    exp_sig_profession = models.CharField(max_length = 1500, null = True, blank = True)
    exp_sig_specialist = models.CharField(max_length = 1500, null = True, blank = True)
    exp_sig_experience = models.CharField(max_length = 1500, null = True, blank = True)
    exp_sig_expspecifi = models.CharField(max_length = 1500, null = True, blank = True)
    exp_hidrol = models.FloatField(null = True, blank = True)
    exp_hidrol_fm = models.FloatField(null = True, blank = True)
    exp_hidrol_via = models.FloatField(null = True, blank = True)
    exp_hidrol_profession = models.CharField(max_length = 1500, null = True, blank = True)
    exp_hidrol_specialist = models.CharField(max_length = 1500, null = True, blank = True)
    exp_hidrol_experience = models.CharField(max_length = 1500, null = True, blank = True)
    exp_hidrol_expspecifi = models.CharField(max_length = 1500, null = True, blank = True)
    exp_caliagua = models.FloatField(null = True, blank = True)
    exp_caliagua_fm = models.FloatField(null = True, blank = True)
    exp_caliagua_via = models.FloatField(null = True, blank = True)
    exp_caliagua_profession = models.CharField(max_length = 1500, null = True, blank = True)
    exp_caliagua_specialist = models.CharField(max_length = 1500, null = True, blank = True)
    exp_caliagua_experience = models.CharField(max_length = 1500, null = True, blank = True)
    exp_caliagua_expspecifi = models.CharField(max_length = 1500, null = True, blank = True)
    exp_geolo = models.FloatField(null = True, blank = True)
    exp_geolo_fm = models.FloatField(null = True, blank = True)
    exp_geolo_via = models.FloatField(null = True, blank = True)
    exp_geolo_profession = models.CharField(max_length = 1500, null = True, blank = True)
    exp_geolo_specialist = models.CharField(max_length = 1500, null = True, blank = True)
    exp_geolo_experience = models.CharField(max_length = 1500, null = True, blank = True)
    exp_geolo_expspecifi = models.CharField(max_length = 1500, null = True, blank = True)
    exp_edafo = models.FloatField(null = True, blank = True)
    exp_edafo_fm = models.FloatField(null = True, blank = True)
    exp_edafo_via = models.FloatField(null = True, blank = True)
    exp_edafo_profession = models.CharField(max_length = 1500, null = True, blank = True)
    exp_edafo_specialist = models.CharField(max_length = 1500, null = True, blank = True)
    exp_edafo_experience = models.CharField(max_length = 1500, null = True, blank = True)
    exp_edafo_expspecifi = models.CharField(max_length = 1500, null = True, blank = True)
    exp_cober = models.FloatField(null = True, blank = True)
    exp_cober_fm = models.FloatField(null = True, blank = True)
    exp_cober_via = models.FloatField(null = True, blank = True)
    exp_cober_profession = models.CharField(max_length = 1500, null = True, blank = True)
    exp_cober_specialist = models.CharField(max_length = 1500, null = True, blank = True)
    exp_cober_experience = models.CharField(max_length = 1500, null = True, blank = True)
    exp_cober_expspecifi = models.CharField(max_length = 1500, null = True, blank = True)
    exp_ecosi = models.FloatField(null = True, blank = True)
    exp_ecosi_fm = models.FloatField(null = True, blank = True)
    exp_ecosi_via = models.FloatField(null = True, blank = True)
    exp_ecosi_profession = models.CharField(max_length = 1500, null = True, blank = True)
    exp_ecosi_specialist = models.CharField(max_length = 1500, null = True, blank = True)
    exp_ecosi_experience = models.CharField(max_length = 1500, null = True, blank = True)
    exp_ecosi_expspecifi = models.CharField(max_length = 1500, null = True, blank = True)
    exp_socio = models.FloatField(null = True, blank = True)
    exp_socio_fm = models.FloatField(null = True, blank = True)
    exp_socio_via = models.FloatField(null = True, blank = True)
    exp_socio_profession = models.CharField(max_length = 1500, null = True, blank = True)
    exp_socio_specialist = models.CharField(max_length = 1500, null = True, blank = True)
    exp_socio_experience = models.CharField(max_length = 1500, null = True, blank = True)
    exp_socio_expspecifi = models.CharField(max_length = 1500, null = True, blank = True)
    exp_risk = models.FloatField(null = True, blank = True)
    exp_risk_fm = models.FloatField(null = True, blank = True)
    exp_risk_via = models.FloatField(null = True, blank = True)
    exp_risk_profession = models.CharField(max_length = 1500, null = True, blank = True)
    exp_risk_specialist = models.CharField(max_length = 1500, null = True, blank = True)
    exp_risk_experience = models.CharField(max_length = 1500, null = True, blank = True)
    exp_risk_expspecifi = models.CharField(max_length = 1500, null = True, blank = True)
    prof_soci = models.FloatField(null = True, blank = True)
    prof_soci_fm = models.FloatField(null = True, blank = True)
    prof_soci_via = models.FloatField(null = True, blank = True)
    prof_soci_profession = models.CharField(max_length = 1500, null = True, blank = True)
    prof_soci_specialist = models.CharField(max_length = 1500, null = True, blank = True)
    prof_soci_experience = models.CharField(max_length = 1500, null = True, blank = True)
    prof_soci_expspecifi = models.CharField(max_length = 1500, null = True, blank = True)
    prof_sig = models.FloatField(null = True, blank = True)
    prof_sig_fm = models.FloatField(null = True, blank = True)
    prof_sig_via = models.FloatField(null = True, blank = True)
    prof_sig_profession = models.CharField(max_length = 1500, null = True, blank = True)
    prof_sig_specialist = models.CharField(max_length = 1500, null = True, blank = True)
    prof_sig_experience = models.CharField(max_length = 1500, null = True, blank = True)
    prof_sig_expspecifi = models.CharField(max_length = 1500, null = True, blank = True)
    prof_hidric = models.FloatField(null = True, blank = True)
    prof_hidric_fm = models.FloatField(null = True, blank = True)
    prof_hidric_via = models.FloatField(null = True, blank = True)
    prof_hidric_profession = models.CharField(max_length = 1500, null = True, blank = True)
    prof_hidric_specialist = models.CharField(max_length = 1500, null = True, blank = True)
    prof_hidric_experience = models.CharField(max_length = 1500, null = True, blank = True)
    prof_hidric_expspecifi = models.CharField(max_length = 1500, null = True, blank = True)
    prof_edafo = models.FloatField(null = True, blank = True)
    prof_edafo_fm = models.FloatField(null = True, blank = True)
    prof_edafo_via = models.FloatField(null = True, blank = True)
    prof_edafo_profession = models.CharField(max_length = 1500, null = True, blank = True)
    prof_edafo_specialist = models.CharField(max_length = 1500, null = True, blank = True)
    prof_edafo_experience = models.CharField(max_length = 1500, null = True, blank = True)
    prof_edafo_expspecifi = models.CharField(max_length = 1500, null = True, blank = True)
    prof_bioti = models.FloatField(null = True, blank = True)
    prof_bioti_fm = models.FloatField(null = True, blank = True)
    prof_bioti_via = models.FloatField(null = True, blank = True)
    prof_bioti_profession = models.CharField(max_length = 1500, null = True, blank = True)
    prof_bioti_specialist = models.CharField(max_length = 1500, null = True, blank = True)
    prof_bioti_experience = models.CharField(max_length = 1500, null = True, blank = True)
    prof_bioti_expspecifi = models.CharField(max_length = 1500, null = True, blank = True)
    prof_geol = models.FloatField(null = True, blank = True)
    prof_geol_fm = models.FloatField(null = True, blank = True)
    prof_geol_via = models.FloatField(null = True, blank = True)
    prof_geol_profession = models.CharField(max_length = 1500, null = True, blank = True)
    prof_geol_specialist = models.CharField(max_length = 1500, null = True, blank = True)
    prof_geol_experience = models.CharField(max_length = 1500, null = True, blank = True)
    prof_geol_expspecifi = models.CharField(max_length = 1500, null = True, blank = True)
    aux_socio = models.FloatField(null = True, blank = True)
    aux_socio_fm = models.FloatField(null = True, blank = True)
    aux_socio_via = models.FloatField(null = True, blank = True)
    aux_socio_profession = models.CharField(max_length = 1500, null = True, blank = True)
    aux_socio_specialist = models.CharField(max_length = 1500, null = True, blank = True)
    aux_socio_experience = models.CharField(max_length = 1500, null = True, blank = True)
    aux_socio_expspecifi = models.CharField(max_length = 1500, null = True, blank = True)
    aux_hidri = models.FloatField(null = True, blank = True)
    aux_hidri_fm = models.FloatField(null = True, blank = True)
    aux_hidri_via = models.FloatField(null = True, blank = True)
    aux_hidri_profession = models.CharField(max_length = 1500, null = True, blank = True)
    aux_hidri_specialist = models.CharField(max_length = 1500, null = True, blank = True)
    aux_hidri_experience = models.CharField(max_length = 1500, null = True, blank = True)
    aux_hidri_expspecifi = models.CharField(max_length = 1500, null = True, blank = True)
    aux_bioti = models.FloatField(null = True, blank = True)
    aux_bioti_fm = models.FloatField(null = True, blank = True)
    aux_bioti_via = models.FloatField(null = True, blank = True)
    aux_bioti_profession = models.CharField(max_length = 1500, null = True, blank = True)
    aux_bioti_specialist = models.CharField(max_length = 1500, null = True, blank = True)
    aux_bioti_experience = models.CharField(max_length = 1500, null = True, blank = True)
    aux_bioti_expspecifi = models.CharField(max_length = 1500, null = True, blank = True)
#    watersheed = models.CharField(max_length = 500, null = True, blank = True)
#    aprest_transpor_unitario = models.FloatField(null = True, blank = True)
#    aprest_transpor_cantidad = models.IntegerField(null = True, blank = True)
#    diag_estudio_coberturas = models.FloatField(null = True, blank = True)
#    diag_estudio_multitemporal = models.FloatField(null = True, blank = True)
#    diag_estudio_plana = models.FloatField(null = True, blank = True)
#    diag_estudio_ladera = models.FloatField(null = True, blank = True)
#    diag_estudio_geologica = models.FloatField(null = True, blank = True)
#    diag_estudio_electricos = models.FloatField(null = True, blank = True)
#    diag_estudio_caliagua = models.FloatField(null = True, blank = True)
#    diag_estudio_ecologica = models.FloatField(null = True, blank = True)
#    diag_transpor_unitario = models.FloatField(null = True, blank = True)
#    diag_transpor_cantidad = models.FloatField(null = True, blank = True)
#    zoni_transpor_unitario = models.FloatField(null = True, blank = True)
#    zoni_transpor_cantidad = models.IntegerField(null = True, blank = True)
#    formula_transpor_unitario = models.FloatField(null = True, blank = True)
#    formula_transpor_cantidad = models.IntegerField(null = True, blank = True)

class refBaseTeam(models.Model):
    cargoname = models.CharField(max_length = 50)
    aprestarq = models.BooleanField()
    diagnosrq = models.BooleanField()
    prospecrq = models.BooleanField()
    formularq = models.BooleanField()
    remunedef = models.FloatField()
    factmudef = models.FloatField()
    viaticdef = models.FloatField()
    categodef = models.IntegerField()

    def __unicode__(self):
        return self.cargoname

class pomcasPhase(models.Model):
    phasename = models.CharField(max_length = 50)

    def __unicode__(self):
        return self.phasename

class TeamDedicat(models.Model):
    workernam = models.ForeignKey('refBaseTeam')
    pomcaphas = models.ForeignKey('pomcasPhase')
    watareami = models.FloatField()
    watareama = models.FloatField()
    watdedimi = models.FloatField()
    watdedima = models.FloatField()
    activetim = models.IntegerField()

    def __unicode__(self):
        return "%s (%s)." % (self.workernam, self.pomcasphas)
